SistemaGeolocalizacion/SistemaGeolocalizacion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('centroinvestigacion.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('busqueda/', include('busquedas.urls')),

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SistemaGeolocalizacion/centroinvestigacion/urls.py
from django.urls import path
from centroinvestigacion import views, views_enfoque
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


handler404 = 'centroinvestigacion.views.error_404'

urlpatterns = [
    path('', views_enfoque.PaginaInicio.as_view(), name='bienvenida'),
    path('centros', views.ListaCentros.as_view(), name='centros_lista'),
    path('centro/nuevo', views.NuevoCentro.as_view(), name='nuevo_centro'),
    path('centro/editar/<int:pk>', views.EditarCentro.as_view(), name='editar_centro'),
    path('centro/eliminar/<int:pk>',
         views.EliminarCentro.as_view(), name='eliminar_centro'),
    path('centro/detalles/<int:id>', views.detalles_centros, name='detalles_centro'),
    

    path('enfoques', views_enfoque.ListaEnfoques.as_view(), name='enfoques_lista'),
    path('enfoques/nuevo', views_enfoque.NuevoEnfoqueView.as_view(),
         name='nuevo_enfoque'),
    path('enfoques/editar/<int:pk>',
         views_enfoque.EditarEnfoqueView.as_view(), name='editar_enfoque'),
    path('enfoques/eliminar/<int:pk>',
         views_enfoque.EliminarEnfoqueView.as_view(), name='eliminar_enfoque'),
]

SistemaGeolocalizacion/usuarios/urls.py
from django.urls import path
# from centroinvestigacion import views, views_enfoque
from usuarios import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('salir', LogoutView.as_view(), name='logout'),
    path('entrar', views.LoginView.as_view(), name='login'),
    path('registrar', views.RegistrarView.as_view(), name='registrar'),


]

SistemaGeolocalizacion/centroinvestigacion/models.py
from django.db import models


class CentroInvestigacion(models.Model):
    nombre = models.CharField(max_length=50, unique=True, blank=False)
    calle = models.CharField(
        'Calle', max_length=150, null=False, blank=False)
    colonia = models.CharField(
        'Colonia', max_length=150, null=False, blank=False)
    numExterior = models.CharField(
        'Numero Exterior', max_length=5, null=False, blank=False)
    cp = models.CharField(
        'Codigo Postal', max_length=5, null=False, blank=False)
    estado = models.CharField(
        'Estado', max_length=150, null=False, blank=False)
    municipio = models.ForeignKey("centroinvestigacion.Municipio", verbose_name="Municipio",
        on_delete=models.DO_NOTHING, null=False, blank=False)
    latitud = models.CharField(max_length=20, unique=True, blank=False)
    longitud = models.CharField(max_length=20, unique=True, blank=False)
    telefono = models.CharField(
        'Telefono', max_length=10, unique=True, blank=False)
    areaEnfoque = models.ForeignKey("centroinvestigacion.Area", verbose_name="Area",
                                on_delete=models.DO_NOTHING, null=False, blank=False)
    subAreaEnfoque = models.ForeignKey("centroinvestigacion.Enfoque", verbose_name="Subarea",
                                on_delete=models.DO_NOTHING, null=False, blank=False)
    sitioWeb = models.CharField(max_length=100, unique=True, blank=True)
    imagen = models.ImageField(null = True, blank = True, upload_to = 'foto/')
    logotipo = models.ImageField(null = True, blank = True, upload_to = 'logos/')
    nombreEncargado = models.CharField('Nombre',max_length=100, unique=True, blank=False)
    correoEncargado = models.CharField('Correo',max_length=50, unique=True, blank=False)
    telefonoEncargado = models.CharField('Teléfono',max_length=10, unique=True, blank=False)


    def __str__(self):
        return self.nombre

class Enfoque(models.Model):
    area = models.ForeignKey("centroinvestigacion.Area", verbose_name="Area",
                                on_delete=models.DO_NOTHING, null=False, blank=False)
    subarea = models.CharField(
        max_length=50, unique=True, blank=False, null=False)
    descripcion = models.CharField(
        'Descripción', null=False, blank=False, max_length=150)

    def __str__(self):
        return self.subarea

class Area(models.Model):
    nombre = models.CharField(
        max_length=150, unique=True, blank=False, null=False)

    def __str__(self):
        return self.nombre

class Municipio(models.Model):
    nombre = models.CharField(max_length=150, unique=True, blank=False, null=False)

    def __str__(self):
        return self.nombre

SistemaGeolocalizacion/centroinvestigacion/forms.py
from django import forms
from centroinvestigacion.models import CentroInvestigacion, Enfoque


class FormCentroInvestigacion(forms.ModelForm):


    class Meta:
        model = CentroInvestigacion
        fields = '__all__'

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'calle': forms.TextInput(attrs={'class': 'form-control'}),
            'colonia': forms.TextInput(attrs={'class': 'form-control'}),
            'numExterior': forms.TextInput(attrs={'class': 'form-control'}),
            'cp': forms.TextInput(attrs={'class': 'form-control'}),                                                
            'estado': forms.TextInput(attrs={'class': 'form-control', 'value':'Zacatecas', 'readonly': 'true'}),
            'municipio': forms.Select(attrs={'class': 'form-control'}),
            'latitud': forms.TextInput(attrs={'class': 'form-control', 'readonly' : 'true'}),
            'longitud': forms.TextInput(attrs={'class': 'form-control', 'readonly': 'true'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'areaEnfoque': forms.Select(attrs={'class': 'form-select'}),
            'subAreaEnfoque': forms.Select(attrs={'class': 'form-select'}),
            'sitioWeb': forms.TextInput(attrs={'class': 'form-control'}),
            'nombreEncargado': forms.TextInput(attrs={'class': 'form-control'}),
            'correoEncargado': forms.TextInput(attrs={'class': 'form-control'}),
            'telefonoEncargado': forms.TextInput(attrs={'class': 'form-control'}),
        }

        imagen = forms.ImageField(widget=forms.ImageField())
        logotipo = forms.ImageField(widget=forms.ImageField())


        def __init__(self, *args, **kwargs):
            super(FormCentroInvestigacion, self).__init__(*args, **kwargs)
            self.fields['imagen'].required = False
            self.fields['logotipo'].required = False



class FormEnfoque(forms.ModelForm):

    class Meta:
        model = Enfoque
        fields = '__all__'

        widgets = {
            'area': forms.Select(attrs={'class': 'form-control'}),
            'subarea': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.TextInput(attrs={'class': 'form-control'}),

        }

SistemaGeolocalizacion/centroinvestigacion/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.conf import settings

from centroinvestigacion.models import Area, Enfoque, CentroInvestigacion
from centroinvestigacion.forms import FormCentroInvestigacion
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect






class ListaCentros(LoginRequiredMixin, ListView):
    model = CentroInvestigacion

class NuevoCentro(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = CentroInvestigacion
    form_class = FormCentroInvestigacion
    success_url = reverse_lazy('centros_lista')
    extra_context = {'accion': 'Nuevo'}
    success_message = "Se agregó el centro de investigación correctamente"

    context_object_name = 'obj'

    def get_context_data(self, **kwargs):
        context = super(NuevoCentro, self).get_context_data(**kwargs)
        context["areaEnfoque"] = Area.objects.all()
        context["subAreaEnfoque"] = Enfoque.objects.all()
        return context

    def clean_nombre_centro(self, form):
        nombre = form.cleaned_data['nombre']
        if CentroInvestigacion.objects.filter(nombre=nombre).exists():
            messages.error(self.request, 'El nombre del centro o laboratorio ya se encuentra registrado.')
        return nombre

    def clean_telefono_centro(self, form):
        telefono = form.cleaned_data['telefono']
        if CentroInvestigacion.objects.filter(telefono=telefono).exists():
            raise forms.ValidationError('El teléfono del centro o laboratorio ya se encuentra registrado.')
        return telefono

    def clean_nombreEncargado(self, form):
        nombreEncargado = form.cleaned_data['nombreEncargado']
        if CentroInvestigacion.objects.filter(nombreEncargado=nombreEncargado).exists():
            raise forms.ValidationError('El nombre del encargado ya se encuentra registrado.')
        return nombreEncargado

    def obtener_api(request):
        return render(request, {'api_key': settings.GOOGLE_MAPS_API_KEY})
    


class EditarCentro(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = CentroInvestigacion
    form_class = FormCentroInvestigacion
    success_url = reverse_lazy('centros_lista')
    extra_context = {'accion' : 'Editar'}
    success_message = "Se editó la información correctamente"

    context_object_name = 'obj'

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        context = super(EditarCentro, self).get_context_data(**kwargs)
        context["areaEnfoque"] = Area.objects.all()
        context["subAreaEnfoque"] = Enfoque.objects.all()
        context["obj"] = CentroInvestigacion.objects.filter(pk=pk).first()
        return context

    def obtener_api(request):
        return render(request, {'api_key': settings.GOOGLE_MAPS_API_KEY})



class EliminarCentro(LoginRequiredMixin, DeleteView):
    model = CentroInvestigacion
    success_url = reverse_lazy('centros_lista')

    def form_valid(self, form):
        self.object = self.get_object()
        self.object.delete()
        messages.success(self.request, 'Se eliminó con éxito')
        success_url = self.get_success_url()
        return HttpResponseRedirect(success_url)

@login_required
def detalles_centros(request, id):
    if request.method == 'GET':
        centro = CentroInvestigacion.objects.get(id=id)
        # print(centro.nombre + centro.direccion)
        return render(request, 'detalles_centro.html', {'centros': centro, 'api_key':settings.GOOGLE_MAPS_API_KEY})

def error_404(request, exception):
    return render(request, '404.html')

SistemaGeolocalizacion/centroinvestigacion/templates/centroinvestigacion/centroinvestigacion_confirm_delete.html
{% extends 'index.html' %}

{% block contenido %}
    <form method = "post">
        {% csrf_token %}
        <p>¿Deseas eliminar el centro <b>{{object}}</b>?</p>
        <input type="submit" value="Eliminar" class="btn btn-danger">
        <a class = "btn btn-secondary" href="{% url 'centros_lista' %}">Regresar</a>
    </form>
{% endblock contenido %}

SistemaGeolocalizacion/centroinvestigacion/templates/centroinvestigacion/centroinvestigacion_form.html
{% extends 'index.html' %}
{% block titulo %}
    {{accion}} Centro de Investigación
{% endblock titulo %}

{% block headers %}
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <style>
        #map{
            height: 400px;
        }

        html,
        body {
            height: 100%;
        }
    </style>

{% endblock headers %}

{% block contenido %}
    <div class = "row">
        <div class="card-body d-flex justify-content-between align-items-center">
            <div class = "col">
                <h1>{{accion}} Laboratorio y/o Centro de Investigación</h1>
            </div>
        </div>

        <div class = "col-sm-10 col-lg-10">
            {% if form.errors %}
              <div class = "alert alert-warning">
                {{form.errors}}
              </div>
            {% endif %}
            <form action="" method="post" enctype = "multipart/form-data" class = "">
                {% csrf_token %}
                <div class = "well well-lg">
                    <h6><b>Datos del Centro:</b></h6>
                    <div class = "row">
                        <div class = "col"><p id="colorLetrasForm">{{form.nombre.label}}: {{form.nombre}}</p></div>
                        <div class = "col"><p id="colorLetrasForm">{{form.telefono.label}}: {{form.telefono}}</p></div>
                    </div>
                    <div class = "row">
                        <div class = "col"><p id="colorLetrasForm">{{form.areaEnfoque.label}}:
                            <select name="areaEnfoque" id="id_areaEnfoque" class = "form-control">
                                <option value = "0">-Selecciona una Opción-</option>
                                {% for area in areaEnfoque %}
                                    <option value="{{area.id}}">{{area.nombre}}</option>
                                {% endfor %}
                            </select></p>
                        </div>
                        <div class = "col"><p id="colorLetrasForm">{{form.subAreaEnfoque.label}}:
                            <select name="subAreaEnfoque" id="id_subAreaEnfoque" class = "form-control">
                                <option value = "0">-Selecciona una Opción-</option>
                                {% for subarea in subAreaEnfoque %}
                                    <option value="{{subarea.id}}" data-chained = "{{subarea.area.id}}">{{subarea.subarea}}</option>
                                {% endfor %}
                            </select></p>
                        </div>
                    </div>
                    <p></p>
                    <div class = "row">
                        <div class = "col"><p id="colorLetrasForm">{{form.sitioWeb.label}}: {{form.sitioWeb}}</p></div>
                        <div class="col"><p id="colorLetrasForm">{{form.imagen.label}}: {{form.imagen}}</p></div>
                        <div class = "col"><p id="colorLetrasForm">{{form.logotipo.label}}: {{form.logotipo}}</p></div>
                    </div>
                    <p></p>

                    <h6><b>Datos del Contacto(Responsable):</b></h6>
                    <div class = "row">
                        <div class = "col"><p id="colorLetrasForm">{{form.nombreEncargado.label}}: {{form.nombreEncargado}}</p></div>
                        <div class = "col"><p id="colorLetrasForm">{{form.correoEncargado.label}}: {{form.correoEncargado}}</p></div>
                        <div class = "col"><p id="colorLetrasForm">{{form.telefonoEncargado.label}}: {{form.telefonoEncargado}}</p></div>
                    </div>
                    <p></p>

                    <h6><b>Domicilio:</b></h6>
                    <div class = "row">
                        <div class = "col"><p id="colorLetrasForm">{{form.calle.label}}: {{form.calle}}</p></div>
                        <div class = "col"><p id="colorLetrasForm">{{form.numExterior.label}}: {{form.numExterior}}</p></div>
                    </div>
                    <p></p>
                    <div class = "row">
                        <div class = "col"><p id="colorLetrasForm">{{form.colonia.label}}: {{form.colonia}}</p></div>
                        <div class = "col"><p id="colorLetrasForm">{{form.cp.label}}: {{form.cp}}</p></div>
                    </div>
                    <p></p>
                    <div class = "row">
                        <div class = "col"><p id="colorLetrasForm">{{form.estado.label}}: {{form.estado}}</p></div>
                        <div class = "col"><p id="colorLetrasForm">{{form.municipio.label}}: {{form.municipio}}</p></div>
                    </div>

                </div>

                <div class = "well">
                    <div class="row">
                        <div class="col">
                            <h6><b>Geolocalización: Para una mejor presición, arrastrar el marcador a la posicion exacta</b></h6>
                        </div>
                        <div class = "row">
                            <div class = "col" hidden>{{form.latitud.label}}: {{form.latitud}}</div>
                            <div class = "col" hidden>{{form.longitud.label}}: {{form.longitud}}</div>
                            <input class="btn btn-success" type="button" value="Agregar Marcador" onclick="return direccion();">
                        </div>
                    </div>
                        <p></p>
                    <div id = "map"></div>
                </div>

                <div class = "col">
                    <input class= "btn btn-success" type="submit"
                    {% if accion == 'Nuevo' %}
                        value = "Agregar"
                    {% else %}
                        value = "Guardar"
                    {% endif %}
                    >
                    <a class= "btn btn-danger" href="{% url 'centros_lista' %}">Regresar</a>
                </div>
            </form>
        </div>
    </div>

{% endblock contenido %}


{% block scripts %}
<script
    src="https://maps.googleapis.com/maps/api/js?key= Sustituir por API KEY &callback=initMap&v=weekly"
    async
></script>
<script>

    {% if accion == 'Editar' %}
        var marker;
        var geocoder;
        var map;

        latitudE = $('#id_latitud').val()
        longitudE = $('#id_longitud').val()

        function initMap() {

            geocoder = new google.maps.Geocoder();
            map = new google.maps.Map(document.getElementById("map"), {
            center: { lat: parseFloat(latitudE), lng: parseFloat(longitudE) },
            zoom: 16,
            });
            

            marker = new google.maps.Marker({
                map,
                draggable: true,
                animation: google.maps.Animation.BOUNCE,
                position: { lat: parseFloat($('#id_latitud').val()), lng: parseFloat( $('#id_longitud').val()) },
            });
            marker.addListener("dragend", toggleBounce);
        }
        function direccion() {
            var calle = document.getElementById('id_calle').value;
            var numero = document.getElementById('id_numExterior').value;
            var colonia = document.getElementById('id_colonia').value;
            var cp = document.getElementById('id_cp').value;
            var estado = document.getElementById('id_estado').value;
            var municipio = document.getElementById('id_municipio').value;

            var direccion = calle + ' ' + numero + ', ' + colonia + ', ' + cp + ', ' + estado + ', ' + municipio;
            console.log(direccion);
            geocoder.geocode( { 'address': direccion}, function(results, status) {
                if(status == 'OK'){
                    map.setCenter(results[0].geometry.location);
                    map.setZoom(18);
                    marker.setPosition(results[0].geometry.location);
                    // marker = new google.maps.Marker({
                    //     map: map,
                    //     position: results[0].geometry.location,
                    //     draggable: true,
                    // });
                } else {
                    alert('No se pudo agregar el marcador correctamente por la siguiente razon: No se agregó una dirección');
                }
            });
            marker.addListener("dragend", toggleBounce);

        }
    {% else %}
        var geocoder;
        var map;
        var marker;
        function initMap() {
            geocoder = new google.maps.Geocoder();
            map = new google.maps.Map(document.getElementById("map"), {
                center: { lat: 22.766050981989335, lng: -102.5697492675781 },
                zoom: 11,
            });
        

            marker = new google.maps.Marker({
                map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: { lat: 22.766050981989335, lng: -102.5697492675781 },
            });
        }

        function direccion() {
            var calle = document.getElementById('id_calle').value;
            var numero = document.getElementById('id_numExterior').value;
            var colonia = document.getElementById('id_colonia').value;
            var cp = document.getElementById('id_cp').value;
            var estado = document.getElementById('id_estado').value;
            var municipio = document.getElementById('id_municipio').value;

            var direccion = calle + ' ' + numero + ', ' + colonia + ', ' + cp + ', ' + estado + ', ' + municipio;
            console.log(direccion);
            geocoder.geocode( { 'address': direccion}, function(results, status) {
                if(status == 'OK'){
                    map.setCenter(results[0].geometry.location);
                    marker.setPosition(results[0].geometry.location);
                    // marker = new google.maps.Marker({
                    //     map: map,
                    //     position: results[0].geometry.location,
                    //     draggable: true,
                    // });
                } else {
                    alert('No se pudo agregar el marcador correctamente por la siguiente razon: No se agregó una dirección');
                }
            });
            marker.addListener("dragend", toggleBounce);

        }

    {% endif %}

    function toggleBounce() {

        marker.setAnimation(google.maps.Animation.BOUNCE);
        $('#id_latitud').val(marker.position.lat);
        $('#id_longitud').val(marker.position.lng);

    }
    
    window.initMap = initMap;

</script>    
    
<script>
    $(function(){
        $("#id_areaEnfoque").val("{{ obj.subAreaEnfoque.area.id }}").change();
        $("#id_subAreaEnfoque").val("{{ obj.subAreaEnfoque.id }}").change();
        $("#id_subAreaEnfoque").chained("#id_areaEnfoque");
    });
</script>
{% endblock scripts %}

SistemaGeolocalizacion/centroinvestigacion/templates/centroinvestigacion/centroinvestigacion_list.html
{% extends 'index.html' %}

{% block titulo %}
    Lista de Laboratorios/Centros
{% endblock titulo %}

{% block contenido %}

    <div class="row">
        <div class="card-body d-flex justify-content-between align-items-center">
            <h2>Laboratorios y Centros de Investigación</h2>
            <a class = "btn btn-success btn-sm" href="{% url 'nuevo_centro' %}">Nuevo</a>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class = "alert alert-danger">
                    {{message}}
                </div>
            {% else %}
                <div class = "alert alert-success">
                    {{message}}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <table class = "table table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Area de Investigación</th>
                <th>Subarea</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for centro in object_list %}
                <tr>
                    <td>{{centro.nombre}}</td>
                    <td>{{centro.areaEnfoque}}</td>
                    <td>{{centro.subAreaEnfoque}}</td>
                    <td>
                        <a class = "btn btn-primary btn-sm" href="{% url 'editar_centro' centro.id %}">Editar</a>
                        <a class = "btn btn-warning btn-sm" href="{% url 'detalles_centro' centro.id %}">Ver detalles</a>
                        <a class = "btn btn-danger btn-sm" href="{% url 'eliminar_centro' centro.id %}">Eliminar</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="8">
                        <p>No existen centros de Investigación registrados</p>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}

SistemaGeolocalizacion/centroinvestigacion/templates/centroinvestigacion/enfoque_confirm_delete.html
{% extends 'index.html' %}

{% block contenido %}
    <form method = "post">
        {% csrf_token %}
        <p>¿Deseas eliminar el enfoque <b>{{object}}</b>?</p>
        <input type="submit" value="Eliminar" class="btn btn-danger">
        <a class = "btn btn-secondary" href="{% url 'enfoques_lista' %}">Regresar</a>
    </form>
{% endblock contenido %}

SistemaGeolocalizacion/centroinvestigacion/templates/centroinvestigacion/enfoque_form.html
{% extends 'index.html' %}
{% block titulo %}
    {{accion}} Enfoque
{% endblock titulo %}

{% block contenido %}
    <div class="row">
        <div class="card-body d-flex justify-content-between align-items-center">
            <div class="col">
                <h1>{{accion}} Enfoque para Centro de Investigación</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10 col-lg-10">
            {% if messages %}
                {% for message in messages %}
                    <div class = "alert alert-danger" role = "alert">
                        {{ message }}
                    </div>
                {% endfor %}
             {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                <div class="well well-lg">
                    <h6><b>Datos del Enfoque:</b></h6>
                    <div class="row">
                        <div class="col">{{form.area.label}}: {{form.area}}</div>
                        <div class="col">{{form.subarea.label}}: {{form.subarea}}</div>
                    </div>
                    <p></p>
                    <div class="row">
                        <div class="col">{{form.descripcion.label}}: {{form.descripcion}}</div>
                    </div>
                </div>
                <div class = "col">
                    <input class= "btn btn-success" type="submit" 
                        {% if accion == 'Nuevo' %}
                            value = "Agregar"
                        {% else %}
                            value = "Guardar"
                        {% endif %}
                    >
                    <a class= "btn btn-danger" href="{% url 'enfoques_lista' %}">Regresar</a>
                </div>
            </form>
        </div>
    </div>
    
{% endblock contenido %}

SistemaGeolocalizacion/centroinvestigacion/templates/centroinvestigacion/enfoque_list.html
{% extends 'index.html' %}

{% block titulo %}
    Lista de Enfoques
{% endblock titulo %}

{% block contenido %}
    <div class="row">
        <div class="col">
            <h2>Enfoques de los Centros de Investigación del Estado de Zacatecas</h2>
        </div>
        <div class="col">
            <a class = "btn btn-success btn-sm" href="{% url 'nuevo_enfoque' %}">Nuevo</a>
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class = "alert alert-danger">
                    {{message}}
                </div>
            {% else %}
                <div class = "alert alert-success">
                    {{message}}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <table class = "table table-striped">
        <thead>
            <tr>
                <th>Area</th>
                <th>Subarea</th>
                <th>Descripción</th>
            </tr>
        </thead>
        <tbody>
            {% for enfoque in object_list %}
                <tr>
                    <td>{{enfoque.area}}</td>
                    <td>{{enfoque.subarea}}</td>
                    <td>
                        {% if enfoque.descripcion %}
                            {{enfoque.descripcion}}
                        {% else %}
                            No cuenta con descripción
                        {% endif %}
                    </td>
                    <td>
                        <a class= "btn btn-primary btn-sm" href="{% url 'editar_enfoque' enfoque.id %}">Editar</a>
                        <a class = "btn btn-danger btn-sm" href="{% url 'eliminar_enfoque' enfoque.id %}">Eliminar</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">
                        <p>No existen enfoques registrados</p>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}